import "./globals.css";
import FontAwesomeConfig from "./fontawesome";
import AuthGuard from "./components/AuthGuard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body>
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}
