# Generated by Django 5.1.6 on 2025-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='communityApp.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='communityApp.profile'),
        ),
    ]
