# Generated by Django 5.1.6 on 2025-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0002_post_dislikes_post_dislikes_count_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_based_on',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
