# Generated by Django 5.1.6 on 2025-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0011_alter_profile_bannerimage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='bannerImage_url',
            field=models.URLField(default='https://res.cloudinary.com/dttdxreiq/image/upload/v1740691299/vlcgkfx6ul17fvokugpv.png'),
        ),
        migrations.AlterField(
            model_name='community',
            name='communityImage_url',
            field=models.URLField(default='https://res.cloudinary.com/dttdxreiq/image/upload/v1740721608/x4nd59qhqts2l670xzwx.png'),
        ),
    ]
