# Generated by Django 5.1.6 on 2025-03-08 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0012_alter_community_bannerimage_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('text_field', models.TextField(max_length=1000)),
                ('media_file', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communityApp.profile')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communityApp.community')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='communityApp.profile')),
                ('saves', models.ManyToManyField(blank=True, related_name='saved_posts', to='communityApp.profile')),
                ('shares', models.ManyToManyField(blank=True, related_name='shared_posts', to='communityApp.profile')),
            ],
        ),
    ]
